### ISSUE TITLE
Topic based pubsub

### ISSUE THREAD

**Issue by aliihsancengiz** [eclipse-ecal/tcp_pubsub#10]
Not only ip+port based pub/sub , but also topic based pub/sub mechanism would be greet.

Eg:

`tcp_pubsub::Publisher hello_world_publisher(executor, "/home/room1/lamp");`

`auto session1 = hello_world_subscriber.addSession("/home/room1/lamp");`

**Comment by FlorianReimold** [comment]
Hi @aliihsancengiz,

TCP is a protocol that always communicates between IP addresses and ports. So in the end, such a technique will have to map that string `"/home/room1/lamp"` to one or multiple ports. How this mapping happens and how the topics are discovered by other publishers and subscribers is not at all trivial.

tcp_pubsub has been developed with the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) in mind and this mapping is not a task that this library wants to do on its own. I recommend you to check out our [eCAL Middleware](https://eclipse-ecal.github.io/ecal/index.html), which uses tcp_pubsub underneath and adds a monitoring- / autoconf-layer for publishing and subscribing on string-based topic names using tcp_pubsub. You only have to [enable it in the ecal.ini file](https://eclipse-ecal.github.io/ecal/advanced/layers/tcp.html#how-to-use).

Regards
Florian

**Comment by aliihsancengiz** [comment]
Hi @FlorianReimold , thank you for your response.
Since tcp_pubsub is lightweight than eCAL Middleware, i just write my opinion about topic based pub/sub since integration with other tools(like Yocto) would be easier. Regarding to the mapping side Distrubuted Hash Table would be a trivial solution. Maybe i will fork this repo in future and try to add a way like mentioned.

Best Regards
Ali ihsan.

**Comment by FlorianReimold** [comment]
That would be awesome, if tcp_pubsub gets used in another middleware! Keep us posted on that! 😀
Obviously, tcp_pubsub is much more lightweight than eCAL - **because** it lacks stuff like topic discovery and so on. This is expected to be implemented by the middleware using tcp_pubsub, while tcp_pubsub takes care of transporting data and simulating a multicast protocol.

But just to mention that: In the past we did compile eCAL for Yocto Linux. It does work! When you disable all the eCAL Apps, HDF5 etc. in your eCAL recipe you end up with the eCAL Core library only, which doesn't have that many dependencies any more and runs on basically any hardware that can run a somewhat recent Linux Kernel.
